### ISSUE TITLE
SpringServlet fails to start using XmlWebApplicationContext on Apache Tomcat

### ISSUE THREAD

**Issue by kuvalda07** [vaadin/spring#382] opened 2018-11-17 08:59 UTC
After updating vaadin from 11.0.1 to 11.0.2 Apache Tomcat fails to start SpringServlet using XmlWebApplicationContext.

org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/app]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1420)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1410)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/app]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 more
Caused by: java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1088)
	at com.vaadin.flow.spring.SpringServlet.isForwardingEnforced(SpringServlet.java:134)
	at com.vaadin.flow.spring.SpringServlet.<init>(SpringServlet.java:53)
	at org.niias.apvo2.dictupdater.Apvo2IntAppInitializer.onStartup(Apvo2IntAppInitializer.java:22)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more

**Comment by kuvalda07** [comment] 2018-11-17 10:05
The issue is encountered when using WebApplicationInitializer, because in vaadin-spring-10.0.6 method isForwardingEnforced is called in SpringServlet-constructor . context.getBean is being called by isForwardingEnforced, but context is not initialized yet.
Workaround: using web.xml, where context is being initialized before the servlet.

**Comment by kuvalda07** [comment] 2018-11-17 10:49
Unfortunately, using web.xml doesn't work.
Server starts, but SpringServlet is not being initialized, because doesn't have a default-constructor.
java.lang.NoSuchMethodException: com.vaadin.flow.spring.SpringServlet.<init>()

Also I suspect, SpringServlet not looks up a spring context, as it was in Vaadin 8 Framework.

**Comment by mehdi-vaadin** [comment] 2020-01-20 08:52
@kuvalda07 since Vaadin 11 is not supported could you check if this bug can be reproduced in Vaadin 14 (e.g. 14.1.5) as well?

**Comment by kuvalda07** [comment] 2020-02-07 13:45
@mehdi-vaadin checked in latest Vaadin (14.1.16), application works fine, bug can't be reproduced.

**Comment by mehdi-vaadin** [comment] 2020-02-07 13:46
@kuvalda07 thank you very much for your time. I'm closing this issue now.

**Closed** 2020-02-07 13:46 UTC
Labels: bug
