### ISSUE TITLE
Error creating bean with name 'com.vaadin.flow.component.icon.IronIcon': No qualifying bean of type 'java.lang.String' available

### ISSUE THREAD

**Issue by mvysny** [vaadin/spring#654] opened 2020-08-24 09:32 UTC
Vaadin 14.3.4, Flow 2.3.4. The following code causes the Spring plugin to fail:

```javascript
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
import '@vaadin/vaadin-button/vaadin-button.js';
import '@polymer/iron-icon/iron-icon.js';

class MyButton extends PolymerElement {
    static get template() {
        return html`
            <vaadin-button theme="tertiary">
                <iron-icon icon="vaadin:bell" slot="suffix"></iron-icon>
            </vaadin-button>
    `;
    }

    static get is() {
        return 'my-button';
    }
}

customElements.define(MyButton.is, MyButton);
```

```java
package org.vaadin.example;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.icon.IronIcon;
import com.vaadin.flow.component.polymertemplate.PolymerTemplate;
import com.vaadin.flow.templatemodel.TemplateModel;

@Tag("my-button")
@Uses(IronIcon.class)
@JsModule("./src/my-button.js")
public class MyButton extends PolymerTemplate<TemplateModel> {
}
```

Exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.vaadin.example.MainView': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.vaadin.example.MainView]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.vaadin.flow.component.icon.IronIcon': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:313) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:294) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:307) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:117) ~[vaadin-spring-12.3.1.jar:na]
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:160) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:135) ~[flow-server-2.3.4.jar:2.3.4]
	at java.base/java.util.Optional.orElseGet(Optional.java:369) ~[na:na]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:134) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:518) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:498) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:230) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.Router.handleNavigation(Router.java:249) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.Router.navigate(Router.java:220) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.Router.navigate(Router.java:186) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.router.Router.initializeUI(Router.java:93) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1534) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:474) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:108) ~[vaadin-spring-12.3.1.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.vaadin.example.MainView]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.vaadin.flow.component.icon.IronIcon': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:309) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 74 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.vaadin.flow.component.icon.IronIcon': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:307) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.vaadin.flow.spring.SpringInstantiator.createComponent(SpringInstantiator.java:70) ~[vaadin-spring-12.3.1.jar:na]
	at com.vaadin.flow.component.ComponentUtil.componentFromElement(ComponentUtil.java:429) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.Component.from(Component.java:497) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$attachComponentIfUses$1(TemplateInitializer.java:150) ~[flow-server-2.3.4.jar:2.3.4]
	at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.attachComponentIfUses(TemplateInitializer.java:149) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.doRequestAttachCustomElement(TemplateInitializer.java:127) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$createSubTemplates$3(TemplateInitializer.java:166) ~[flow-server-2.3.4.jar:2.3.4]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[na:na]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer$ParserData.forEachSubTemplate(TemplateDataAnalyzer.java:147) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.createSubTemplates(TemplateInitializer.java:166) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.initChildElements(TemplateInitializer.java:102) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:90) ~[flow-server-2.3.4.jar:2.3.4]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-2.3.4.jar:2.3.4]
	at org.vaadin.example.MyButton.<init>(MyButton.java:13) ~[classes/:na]
	at org.vaadin.example.MainView.<init>(MainView.java:63) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 76 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 104 common frames omitted
```

The problem lies in the seemingly innocent `@Uses(IronIcon.class)` annotation - when removed, everything starts to work fine.

Expected behavior: Vaadin should not attempt to instantiate IronIcon.

Actual behavior: Vaadin attempts to instantiate IronIcon and fails.

**Comment by mvysny** [comment] 2020-08-24 09:34
Project which reproduces the issue: 
[skeleton-starter-flow-spring.zip](https://github.com/vaadin/spring/files/5116984/skeleton-starter-flow-spring.zip)

**Comment by caalador** [comment] 2020-09-04 05:46
I couldn't reproduce with the spring-skeleton on 14.3-SNAPSHOT and the attached zip doesn't contain any source code.

**Comment by mvysny** [comment] 2020-09-04 07:06
> The attached zip doesn't contain any source code.

Ouch, I'm sorry. I've made sure to package the example project properly now:
[skeleton-starter-flow-spring.zip](https://github.com/vaadin/spring/files/5173162/skeleton-starter-flow-spring.zip)

> Also Uses does define: For PolymerTemplate implementations, used components will also be instantiated if an element with the corresponding `@Tag` value is defined in the template.

You're right, I've totally missed that documentation in the `@Uses` annotation. Now I can see that the code works as intended, and the instantiation exception is just an unfortunate cause of the expected behaviour. Yet, I believe that the behaviour is "surprising" in a way: it's not obvious why the PolymerTemplate should attempt to instantiate the IronIcon since it's not injected via `@Id` annotation into the PolymerTemplate itself. This sounds like the IronIcon is constructed and then simply thrown away, which makes little sense to me, and therefore I perceive this behaviour as unexpected and a bit buggy.

Therefore I'd propose to either:
* reconsider the decision, stop creating such components if they're not referenced via `@Id` and then update the `@Uses` javadoc, or
* Fail with a more informative exception, pointing towards the `@Uses` annotation on the `MyButton` class, urging me to read the javadoc and do something about the annotation itself :-D . Most probably the annotation is actually unnecessary and should simply be removed anyway; yet it's good to have a proper exception message guiding me towards this.

**Comment by Legioth** [comment] 2020-09-05 08:24
This is one of the situations where bad decisions in the past come back to haunt us.

In the beginning of time, we were thinking that if you have a `PolymerTemplate` that contains e.g. `<my-sub-template>` and your project contains a component class with `@Tag("my-sub-template")`, then it would be expected that an instance of that class to be created alongside with the template so that any listeners or such that it would register would actually be used.

We implemented this so that it would scan the classpath for all classes annotated with `@Tag` and register them in a `CustomElementRegistry` that would then be used by `PolymerTemplate` to find classes to automatically instantiate. It turned out that this automatic instantiation was [causing some surprises](https://github.com/vaadin/flow/issues/2486). To deal with that, we made the automatic instantiotion opt-in so that it would happen only based on presence of a matching `@Uses` annotation. The main concern at that time was that developers would have a hard time understanding that they'd need to add `@Uses` whereas there weren't any concerns about the opposite situation that was described here.

In retrospect, it's safe to say that it would have been better to outright remove the feature and require an even more explicit `@Id` field instead. The problem is that we cannot now change how `@Uses` behaves in relationship to `PolymerTemplate` without potentially breaking backwards compatibility. The newly implemented `LitTemplate` that is supposed to eventually repleace `PolymerTemplate` has this mistake corrected.

This functionality has quite much in common with how the more explicit `@Id` mechanism works and most of the implementation is also shared. This also means that it might be challenging to show different error messages depending in which which feature it was that triggered the instantiation.

**Comment by mvysny** [comment] 2020-09-07 05:41
I see, thank you for a thorough explanation. Since the use-case is pretty obscure and the functionality will go away with LitTemplate, I think it's okay to close this bug as won't fix.

However, I can see that the stacktrace points to this method:

```
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$attachComponentIfUses$1(TemplateInitializer.java:150) ~[flow-server-2.3.4.jar:2.3.4]
```

The `TemplateInitializer.attachComponentIfUses()` explicitly deals with `@Uses` only, since it calls `getUsesClass()` which polls in `USES_CACHE` which is populated with `extractUsesMap()` which only consults the `@Uses` annotation. I was thinking of wrapping the call to `Component.from(element, componentClass)` at `TemplateInitializer:150` in a try-catch and provide a more verbose error message, something along `Looks like you're using @Uses with @PolymerTemplate which is a bad idea, see https://github.com/vaadin/spring/issues/654 for more details. Original exception: foo bar`.

That sounds like an easy fix, and definitely something that would remedy this issue. What do you think @Legioth ?

**Comment by Legioth** [comment] 2020-09-08 07:03
Sure. If there is a good place to add a try-catch that wouldn't also affect `@Id`, then that would be a good "workaround".

Though I'm quite sure the clarified error message should have some more nuance rather than saying that something is "a bad idea" :)

**Comment by caalador** [comment] 2020-10-27 06:57
Closing issue as won't fix due to the little impact for the amount of work.

**Closed by caalador** 2020-10-27 06:57 UTC
Labels: PolymerTemplate, waiting for author
