### ISSUE TITLE
Application locks up when using @EnableAsync and @Push simultaneously

### ISSUE THREAD

**Issue by edler-san** [vaadin/spring#471] opened 2019-08-06 11:36 UTC
Upon (multiple) refresh(es) of an application containing a grid and accessing a database via a Spring JpaRepository, the application locks up and shows an empty page. The console shows a java.net.SocketTimeoutException. This only happens when using @EnableAsync and @Push jointly. Each for itself works.

The reproduction of the issue requires to set up a database. The code to reproduce is available via ticket number 3053 in the support portal (due to legal reasons it is not attached here). Detailed instructions can be found there.

**Comment by ujoni** [comment] 2019-09-23 12:11
I have been unable to reproduce this issue. I attempted to refresh the page multiple times. Some time the render delay was couple of seconds, but regardless, the page was finally rendered with all the elements.

**Setup:**
- `postgres:11` running on docker
- App compiled with Java 12, and ran with `mvn spring-boot:run` 
- Windows 10 operating system
- Browsers Chrome 77, Firefox 69

Are there some other steps that should be taken in order to reproduce the issue?

**Comment by heruan** [comment] 2019-09-23 12:58
Thank you @ujoni for trying to reproduce. As this is no longer a priority for me, feel free to close this for now; I'll reopen if/when I'll be able to investigate further.

**Comment by caalador** [comment] 2020-05-22 06:16
Closing issue as there has been no activity towards reproducing the issue for a long while.
Feel free to open a new issue with new details.

**Closed by caalador** 2020-05-22 06:16 UTC
Labels: Impact: Low, Severity: Major, bug, spring, waiting for author
